Cidade = str(input("Digite o nome de sua cidade"))
Analisador = Cidade.capitalize().find("Santos")
print("Se aparecer -1 sua cidade não é Santos")
print("Se não ela é Santos")
print("Cidade digitada", Cidade)
print("Santos?", Analisador)